# Netlify Konfigurationsdatei

[build]
  # Der Befehl, der zum Bauen der Website verwendet wird
  command = "npm run build"
  
  # Das Verzeichnis, in dem die gebaute Website liegt
  publish = "dist"
  
  # Umgebungsvariablen für den Build-Prozess
  [build.environment]
    NODE_VERSION = "18"
    NETLIFY_USE_PRERENDER = "true"
    DEBUG = "netlify-plugin-inline-functions-env"

# Domain redirects - ensure all traffic goes to www.dionhairclinic.com
# Specific redirect for index.html
[[redirects]]
  from = "https://www.dionhairclinic.de/index.html"
  to = "https://www.dionhairclinic.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://dionhairclinic.de/index.html"
  to = "https://www.dionhairclinic.com/"
  status = 301
  force = true

[[redirects]]
  from = "https://dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

# Non-www to www redirect for canonical domain
[[redirects]]
  from = "https://dionhairclinic.com/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

# Redirect for index.html on primary domain
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

# Critical redirect rules - sitemap first, then SPA routing
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# SPA routing (must come after sitemap rule)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header for XML sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=86400"
