# Netlify Konfigurationsdatei

[build]
  # Der Befehl, der zum Bauen der Website verwendet wird
  command = "npm run build"
  
  # Das Verzeichnis, in dem die gebaute Website liegt
  publish = "dist"
  
  # Umgebungsvariablen für den Build-Prozess
  [build.environment]
    NODE_VERSION = "18"
    NETLIFY_USE_PRERENDER = "true"
    DEBUG = "netlify-plugin-inline-functions-env"

# Prevent the Netlify sitemap plugin from running
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    disabled = true

# Critical redirect rules - sitemap first, then SPA routing
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# SPA routing (must come after sitemap rule)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header for XML sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=86400"
