# Netlify Konfigurationsdatei

[build]
  # Der Befehl, der zum Bauen der Website verwendet wird
  command = "npm run build"
  
  # Das Verzeichnis, in dem die gebaute Website liegt
  publish = "dist"
  
  # Umgebungsvariablen für den Build-Prozess
  environment = { NODE_VERSION = "18", NETLIFY_USE_PRERENDER = "true" }

# Disable the default Netlify sitemap plugin
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    exclude = ['**/*']


# SPA routing (must come after sitemap rule)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
