# Netlify Konfigurationsdatei

[build]
  # Der Befehl, der zum Bauen der Website verwendet wird
  command = "npm run build"
  
  # Das Verzeichnis, in dem die gebaute Website liegt
  publish = "dist"
  
  # Umgebungsvariablen für den Build-Prozess
  environment = { NODE_VERSION = "18", NETLIFY_USE_PRERENDER = "true" }

# Prerendering für SEO aktivieren
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    baseUrl = "https://www.dionhairclinic.com"
    changeFreq = "weekly"
    priority = 0.8
    trailingSlash = false
    
    # Alle wichtigen Seiten in die Sitemap aufnehmen
    [[plugins.inputs.include]]
      path = "/"
      priority = 1.0
      
    [[plugins.inputs.include]]
      path = "/haartransplantation"
      priority = 0.9
      
    [[plugins.inputs.include]]
      path = "/barthaartransplantation"
      priority = 0.9
      
    [[plugins.inputs.include]]
      path = "/augenbrauentransplantation"
      priority = 0.9
      
    [[plugins.inputs.include]]
      path = "/preise"
      priority = 0.9
      
    [[plugins.inputs.include]]
      path = "/kontakt"
      priority = 0.8
      
    [[plugins.inputs.include]]
      path = "/klinik"
      priority = 0.8
      
    [[plugins.inputs.include]]
      path = "/wissenswertes"
      priority = 0.8
      
    [[plugins.inputs.include]]
      path = "/impressum"
      priority = 0.3
      
    [[plugins.inputs.include]]
      path = "/datenschutz"
      priority = 0.3
      
    [[plugins.inputs.include]]
      path = "/agb"
      priority = 0.3
      
    [[plugins.inputs.include]]
      path = "/cookies"
      priority = 0.3

# Non-WWW zu WWW Redirects für .com Domain
[[redirects]]
  from = "https://dionhairclinic.com/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dionhairclinic.com/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

# Redirects für .de Domain zu .com Domain
[[redirects]]
  from = "https://www.dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://dionhairclinic.de/*"
  to = "https://www.dionhairclinic.com/:splat"
  status = 301
  force = true

# Weiterleitungsregeln für SPA-Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Header-Konfiguration
[[headers]]
  # Header für alle Dateien definieren
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Header für den Service Worker
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Header für statische Assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
